name: my site
remote_thems: pages-themes/minimal@0.2.0
plagins: - jekyll-remote-theme
title: [NatureBeauty Vitae]
description: 
[Welcome to Nature Beaty Vitae Your guide to an antiaging lifestyle. Here you will find all the information about how to look and feel younger]
